
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.backup.cv.io
  labels:
    api: kexer
    apiserver: "true"
spec:
  version: v1
  group: backup.cv.io
  groupPriorityMinimum: 2000
  service:
    name: kexer
    namespace: kexec-system
  versionPriority: 10
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURxekNDQXBPZ0F3SUJBZ0lVVmlYQUlIMzQySUVwUERONmJPejlhYmhMWHdBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNkVzR4Q3pBSkJnTlZCQWdNQW5OME1Rb3dDQVlEVlFRSERBRnNNUW93Q0FZRApWUVFLREFGdk1Rc3dDUVlEVlFRTERBSnZkVEVrTUNJR0ExVUVBd3diYTJWNFpYSXRZMlZ5ZEdsbWFXTmhkR1V0CllYVjBhRzl5YVhSNU1CNFhEVEl6TVRBeU1ERXdNelF4T0ZvWERUSTBNVEF4T1RFd016UXhPRm93WlRFTE1Ba0cKQTFVRUJoTUNkVzR4Q3pBSkJnTlZCQWdNQW5OME1Rb3dDQVlEVlFRSERBRnNNUW93Q0FZRFZRUUtEQUZ2TVFzdwpDUVlEVlFRTERBSnZkVEVrTUNJR0ExVUVBd3diYTJWNFpYSXRZMlZ5ZEdsbWFXTmhkR1V0WVhWMGFHOXlhWFI1Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdTgwcVQ4SEtHZVNOYnYvYmhENHcKRkVrd2lEVDFMeW1WcGtpMGpXTkJ5MkdyVHRxS292Umtva3dnT09hRGVlajB5cjZMeFkzc1FpMnZPdUtmemQzQgpXZG9sRm1VWjNVZlBvdVJTR2FmYXJMRDl4RDZjeDdQSXlubllTMjd3UlZvTm5mNmVZb3gzUXJQL1dCRGxVZnNQCnNFWFU1b3Z5TDhFU2FpRTg3YkRia3JPNFpudkhQa2NmYWNVNktRUVBIRVJuT3c3S21NTGlzYnJoM0tMTzkzemIKVFhVcHJoNGx0N2pSZGl1VWhST1dHc0ttS0RKTDYrbitmaFo4bXVHMEpzTFJKODh4TFFUYktUUXgwcWdZcEw2dQp4WnpNNXhVTzZNdTRsTUVoQy9wc3diY0taOEFiVlZUbjZ0eExxYTErTHVGNzQ3ZjlQV3phb1RuMmNBZG1SOU5XCkJRSURBUUFCbzFNd1VUQWRCZ05WSFE0RUZnUVVRMXNHalZxaFVGdmJpUkQ4ZHYvMFlSeExWa0F3SHdZRFZSMGoKQkJnd0ZvQVVRMXNHalZxaFVGdmJpUkQ4ZHYvMFlSeExWa0F3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcQpoa2lHOXcwQkFRc0ZBQU9DQVFFQUpKWVdHd3VCODdpYVJRRnp6Y1ZzQkVva1RZUnJyaVQxeTd1M2xFWW5ZOEl5CnM1b3NXUzIzMUppa01YWEZWckZnNUU2NVNlZkVoQ1hmTVlFVUFPL1BGa3Q1QXA4N0hjWnJNZDdjNzVGRVIzWVYKUC9vNjVCM0doSmNwL0UyQnVZZVV0VWp6MjRNdExNYU94UlFhdWJWc3VWeW9GK0J2VGtLcllpY003RU16dFkxWgp4djA5cm9lN2YvdzdnSVliUytHcWNtRGpCQjZZelFqVWF1dGRkVU5CYWJKK280UnZ5Sm1udEgrdFJxMkwzL010Cll2Z1c5ejMxNXpVNUJvRGVsSElmK0gxd2lLVFcweUhZaThtR200aDRCMXd4b1lSdG1GOGMwNUVRbHRraHZob0sKbUo0SjIxV25SL2gwNWFjKzBwaFBOUnlNdGplWUt3bDArZ0d4RjBNUE9nPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
---
