---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kexer
  namespace: kexec-system
  labels:
    api: kexer
    apiserver: "true"
spec:
  selector:
    matchLabels:
      api: kexer
      apiserver: "true"
  replicas: 1
  template:
    metadata:
      labels:
        api: kexer
        apiserver: "true"
    spec:
      serviceAccount: kexer
      containers:
      - name: apiserver
        image: shnkr5/kexer:1
        imagePullPolicy: Always
        volumeMounts:
        - name: apiserver-certs
          mountPath: /apiserver-certs
          readOnly: true
        command:
        - "./apiserver"
        args:
        - "--etcd-servers=http://etcd-svc:2379"
        - "--tls-cert-file=/apiserver-certs/tls.crt"
        - "--tls-private-key-file=/apiserver-certs/tls.key"
        - "--audit-log-path=-"
        - "--feature-gates=APIPriorityAndFairness=false"
        - "--audit-log-maxage=0"
        - "--audit-log-maxbackup=0"
      volumes:
      - name: apiserver-certs
        secret:
          secretName: kexer
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: kexer
  namespace: kexec-system
  labels:
    api: kexer
    apiserver: "true"
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURrRENDQW5pZ0F3SUJBZ0lJZW9HcUt3VjBVNGN3RFFZSktvWklodmNOQVFFTEJRQXdaVEVMTUFrR0ExVUUKQmhNQ2RXNHhDekFKQmdOVkJBZ01Bbk4wTVFvd0NBWURWUVFIREFGc01Rb3dDQVlEVlFRS0RBRnZNUXN3Q1FZRApWUVFMREFKdmRURWtNQ0lHQTFVRUF3d2JhMlY0WlhJdFkyVnlkR2xtYVdOaGRHVXRZWFYwYUc5eWFYUjVNQjRYCkRUSXpNVEF5TURFd016UXhPRm9YRFRNek1UQXhOekV3TXpReE9Gb3dJVEVmTUIwR0ExVUVBeE1XYTJWNFpYSXUKYTJWNFpXTXRjM2x6ZEdWdExuTjJZekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQgpBS0F5MFF4ZnBKU0Y0Vi9BbTNMaGZ0RWV1ak83K3VLVU1KdHdmNCs2L3J6SXdKNGY1cllJNjA4dlFyL0w1bmZSCjJIUVU4Y1c0d2lvZkVQaFBVU1pLa3JPb0ZydXFHcVJ3Q05FdDNaOS9yb3VYRnZJSGRTR0tpaE1iWkhqczZvakMKdmpOc1RrYkRibzdhbC95clVuMFBScFhITzNXNmIyaTJ6a3g4bzQ0ZW5wc2NyWUwwaW5ZWktRNXFzUFpSOTk4QwphNWRRWTUxdEVRVExrekdoN05pVytkY1h5SWdiZk9COWNmeElRWU9iaFJHc05GeVlILzJoTnFwOFFrbVdKSTQ2CjZHT3lLTEw0KzlsTnNMSGhwQjF5THJsZWxwWVVHVklVeTE3aFlkN1gzc2FMV01TZFU1QURGbVV0aDk4aU9kakUKYVR1Wi9rSnZ5Vk1HR1lPU1Rib1lQZEVDQXdFQUFhT0JoekNCaERBT0JnTlZIUThCQWY4RUJBTUNCYUF3SFFZRApWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQjhHQTFVZEl3UVlNQmFBRkVOYkJvMWFvVkJiCjI0a1EvSGIvOUdFY1MxWkFNRElHQTFVZEVRUXJNQ21DQ1d4dlkyRnNhRzl6ZElJV2EyVjRaWEl1YTJWNFpXTXQKYzNsemRHVnRMbk4yWTRjRWZ3QUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBdXo2cnFQOEhCNDcvcnA4egozUVhXZlprNW1ueURGWXlIdjNjQmFDYmE5Q2w0R0JFRERyOGZXOEZMejZ5UVR0d3dHcXNONGZBckd1Q2IwZHRWClRiTzN1U24xV3d4WXRFQXdrbXNRL1ZUQ0ZoM0ZzQkpHQTFRQ0d6eUovVGczbzNpZy9OTU80ZVRVVTIzYndsWWYKSjErVHNrdDhEVVpjV3RDY1k4dFFxNjdDblh1cEh6aTZwby9MMnd5MlpnT3JrNXdwZXlpcllWMTNFZHBLa2JIYQpGSnFieklFRVE0UG1lb1VsNVhpMkVWcktFR3ltQWNwMVpJNFdaU3ZlOVVkc3FtSWJjUFI1bUg0UGdyNmFwT1M0ClpsVlZCMGxZWTMydFpvVmh2Y1Q0REZqTU9Xa0ZZam0zaS9uV0RKQkFYb01EZ2JBeE1MemZaWlphci9EUmJ1NUoKV1hOK21nPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBb0RMUkRGK2tsSVhoWDhDYmN1RiswUjY2TTd2NjRwUXdtM0IvajdyK3ZNakFuaC9tCnRnanJUeTlDdjh2bWQ5SFlkQlR4eGJqQ0toOFErRTlSSmtxU3M2Z1d1Nm9hcEhBSTBTM2RuMyt1aTVjVzhnZDEKSVlxS0V4dGtlT3pxaU1LK00yeE9Sc051anRxWC9LdFNmUTlHbGNjN2RicHZhTGJPVEh5ampoNmVteHl0Z3ZTSwpkaGtwRG1xdzlsSDMzd0pybDFCam5XMFJCTXVUTWFIczJKYjUxeGZJaUJ0ODRIMXgvRWhCZzV1RkVhdzBYSmdmCi9hRTJxbnhDU1pZa2pqcm9ZN0lvc3ZqNzJVMndzZUdrSFhJdXVWNldsaFFaVWhUTFh1RmgzdGZleG90WXhKMVQKa0FNV1pTMkgzeUk1Mk1ScE81bitRbS9KVXdZWmc1Sk51aGc5MFFJREFRQUJBb0lCQUNxL1pLazRuR0pGbDI1RgpwelZ3bHJhV3pIa2hvRUQxNmtLUU1ubllIRUdrRUVJaG9SN1NJbmh1MUJENkIvWFJPVUZBbFlOOVdkS0RsN09xCjlxeVJHYlIzRmhuZHVsNUd4eE9LZWFrbUdSMkdvOGpSMUordXFFbVE5YTZQQ2NhVXNNeG9DanMzeXppemUvc2cKZkZLQzBRTUd0d2NqU0xkWWtKUTRiaXh1WDBSa1puZm5DeTM3Q1hpaTZncXZJck5kUks4T3d5azJzQUVKdEZ3ZAp6UlRkVmswdTUxY0NSZXI3dUpVL1B1WkM0SHYvbldYV01sTW5qemFPb3gwZDNKWFVYelF2dDBtL0o1QWtEYy9XCnVJdG9ZZUhCYlFoUkZCUWpOWmgwM3ZLZVUvSkY5cktJdDVqaU5iRlpTRVd0RXY3TVUrOUcyWXM5c2h0ZmZiNXUKOGltaUt3RUNnWUVBd1lLWkszd2dkdUgwWVdaTFNBY2JVNng4eEZNbUk0STdZdVdVVGljaEU1dnk3VTFJelRULwpER1dNaXBnOEU3aVkreHBLbWtodlN4Wk1Ldy9pZCtTYXJva01WNnMyZnR3ckpYMWFiSzlCMnZYd3JYKzRPcGR1CjVIZGtKR3ZvR2NZS2xwa1dVNzk1ZzVxcU5nQXhINldsWURSK2RTT0wwKy9kOTVXbStmQm9XRFVDZ1lFQTArNWIKeTFpQklzZFZQelBZSGFlbmdLcVp2T3RHVXd3a0lxQ1MvVWMxRjM4NW9ySmVGenY3YXJvNFFmYlMwRGo4WGZPTgpsQmVuN21yRFJhbWt4dGRJeWdISEpFWDNvdkZCQmFUaTZEdlJnamx0T2IvMXpjbi83dTVjejBIS2JzMFFiOVhQCjdVbTMrQ2UvSTRMUTR6Z011ZTB2akpwemtxWWVvVi9NS3VpS1dxMENnWUJyRDdsMHdKa3BqUHZyUTNCVktuRnAKQ3Q2QXRFdytpeGdXTUZTc0pLUDlPR1BmL01sUmw0ZWdzVEpmbjdobFpOVm0zL1gwaEN6bkN6QWJCdy9TSzIyVgpNUWZlSFVEcVVSK2gvMGVmS0J1MGJDdTdvaFVvZlk0QjR6aEptbFh3cEl4SkkrdWhiQ2RyczQrR2p2YWV2c1BQCmhWdU5yWnY0SnhiVW16eWx2ZWZOSFFLQmdHM3hBekcwRWhuR3FwU0ZBcUl2clJkMGFSaTJQTjhzTnpxM2JrbHkKUFRxWlIzNzlaUTVNa1pyR1RCVDhSRlM4bXo3cDhCSlpTMGJGbjlOdHRBdHE5MW5FSGxqVTZ5aGVXMHJnUk00UQo2aGpTVGJWZHZkZ3A2Rms4MG15NlJwZkFUYnlXZ0swcVJ3TzNLdEx6TkFZTHQ1NWtTdngzeTJqU1FLV2Ftc0hQCnJLWnBBb0dBSlgvRUI5Y2Z6dkpFOHFYVlhGTkh1d2tyR2VUb1BtNU16dklKVzN2U3N1eVlDdUo1a3JlZDVhQ3gKVDBtNzEvRzlTaWRpalZjTW1aWmU3MmlaZnNzNDJkbXRRbVpCU1M0M3JTOFFTUW5zSnc3YitHOW5ZR1RBajdFeQpQVkM1Q0I3VXRONWRHOVQrWnM2ZkZIKzdsSFBZS0VEMWVmM3lyUVcreG9lUlMzQjcrTkE9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
apiVersion: v1
kind: Service
metadata:
  name: kexer
  namespace: kexec-system
  labels:
    api: kexer
    apiserver: "true"
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    api: kexer
    apiserver: "true"
