apiVersion: v1
kind: ServiceAccount
metadata:
  name: kexer
  namespace: kexec-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kexer-apiserver-cluster-admin
  namespace: kexec-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    namespace: kexec-system
    name: kexer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kexer-apiserver-auth-reader
rules:
  - apiGroups:
      - ""
    resourceNames:
      - extension-apiserver-authentication
    resources:
      - configmaps
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kexer-apiserver-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kexer-apiserver-auth-reader
subjects:
  - kind: ServiceAccount
    namespace: kexec-system
    name: kexer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kexer-apiserver-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    namespace: kexec-system
    name: kexer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kexer-controller
  namespace: default
rules:
  - apiGroups:
      - 'backup.cv.io'
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - ''
    resources:
      - 'configmaps'
      - 'namespaces'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
  - apiGroups:
      - 'admissionregistration.k8s.io'
    resources:
      - '*'
    verbs:
      - 'list'
      - 'watch'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kexer-controller
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kexer-controller
subjects:
  - kind: ServiceAccount
    namespace: kexec-system
    name: kexer
